// tsup.config.ts
import { defineConfig } from "tsup";

export default defineConfig({
    entry: {
        index: "src/index.ts",
        "extension/bold": "src/extension/Bold.tsx",
        "extension/base": "src/extension/base.ts",
        "extension/italic": "src/extension/Italic.tsx",
        "extension/underline": "src/extension/Underline.tsx",
        "extension/strike": "src/extension/Strike.tsx",
        "extension/subscript": "src/extension/Subscript.tsx",
        "extension/superscript": "src/extension/Superscript.tsx",
        "extension/subandsuperscript": "src/extension/SubAndSuperscript.tsx",
        "extension/clearformat": "src/extension/ClearFormat.tsx",
        "extension/heading": "src/extension/Heading.tsx",
        "extension/font-family": "src/extension/FontFamily.tsx",
        "extension/font-size": "src/extension/FontSize.tsx",
        "extension/history": "src/extension/History.tsx",
        "extension/color": "src/extension/Color.tsx",
        "extension/backgroundcolor": "src/extension/BackgroundColor.tsx",
        "extension/bulletlist": "src/extension/Bulletlist.tsx",
        "extension/orderedlist": "src/extension/Orderlist.tsx",
        "extension/textalign": "src/extension/TextAlign.tsx",
        "extension/indentoutdent": "src/extension/IndentOutdent.tsx",
        "extension/lineheight": "src/extension/LineHeight.tsx",
        "extension/tasklist": "src/extension/TaskList.tsx",
        "extension/link": "src/extension/Link.tsx",
        "extension/image": "src/extension/Image.tsx",
        "extension/blockquote": "src/extension/BlockQuote.tsx",
        "extension/horizontalrule": "src/extension/HorizontalRule.tsx",
        "extension/table": "src/extension/Table.tsx",
        "extension/emoji": "src/extension/Emoji.tsx",
        "extension/hardbreak": "src/extension/HardBreak.tsx",
    },
    format: ["esm", "cjs"],
    dts: true,
    clean: true,
    outDir: "dist",
    external: [
        "react",
        "react-dom",
        "yjs",
        "y-protocols",
        "@tiptap/y-tiptap",
        "@tiptap/extension-collaboration",
        "@tiptap/extension-collaboration-cursor",
    ]
});
